### ISSUE TITLE
Multiple spans

### ISSUE THREAD

**Issue by md1023** [cdepillabout/docs#1]
Hi!

My bash script uses ansi2html to generate some colored diffs. When I run this script myself, everything works as expected. But after I launched my script with python's subprocess, my tags inside html gets overgrowed with lots of spans with "λR;" sign.

How can I trouble shoot this problem?

**Comment by cdepillabout** [comment]
ansi2html was actually created by pixelbeat:
http://www.pixelbeat.org/scripts/ansi2html.sh

I just put it in my repository as a way to have quick access to it when I need it.

It also looks like there is a Python library based off the code from pixelbeat:
 https://pypi.python.org/pypi/ansi2html

You might want to try contacting one of them in order to troubleshoot your script.

If, for some reason, you want to continue using the ansi2html script in my repository, please post some example Python code so I can try to reproduce the issue.

**Comment by md1023** [comment]
Oh. Thank you for information!

I wrote to pixelbeat and wait for an answer...

Using python library makes more sense in my wsgi-case.

Closing issue until more info is found.

**Comment by pixelb** [comment]
The python lib is a separate thing to the ansi2html.sh script.
This particular bug was fixed in the latest version of ansi2html.sh, so I suggest updating
your repo from http://www.pixelbeat.org/scripts/ansi2html.sh
Note the bu triggers because your python subprocess is not setting the locale variables in the environement. Specifically you may want to propagate LANG to the subprocess so that any other UTF8 specific processing is not impacted

**Comment by md1023** [comment]
Thanks, @pixelb! I've inserted `LANG=en_US.UTF-8` into my bash script and voila :)

**Comment by pixelb** [comment]
Just to reiterate, you shouldn't need that workaround with the latest version of http://www.pixelbeat.org/scripts/ansi2html.sh

**Comment by md1023** [comment]
It was awful and embarassing. One of my browsers cached your link. I did double check... but not with this browser. Everything's fine with the last version without LANG hack.

**Comment by pixelb** [comment]
no worries, I think that may have been partly my fault. I edited the file without changing timestamps,
assuming client/apache combo would cache appropriately using etags. Rather than leave that to chance I've now added "RequestHeader unset If-Modified-Since" to my apache config
